; PlatformIO Project Configuration File
;
; Assignment firmware workspace

[env:adafruit_feather_esp32s3]
platform = espressif32
board = adafruit_feather_esp32s3
framework = arduino
monitor_speed = 115200

